#!/usr/bin/python2

import unittest
import sys, os
sys.path.append(os.path.join(os.path.dirname(sys.argv[0]), '..'))
from base import GhostTestCase

class TestCase(GhostTestCase):
	def do_testcase(self):
		self.ghost.open("https://duckduckgo.com/")
		assert 'search' in self.ghost.content
		result, resources = self.ghost.fill("form", {
			"q": "linux"
		})
		page, resources = self.ghost.fire_on("form", "submit", expect_loading=True)
		assert 'llinux' in self.ghost.content

if __name__ == '__main__':
	del GhostTestCase
	unittest.main()
