#!/usr/bin/python2

import unittest
import sys, os
sys.path.append(os.path.join(os.path.dirname(sys.argv[0]), '..'))
from base import *

class TestCase(GhostTestCase):
	def do_testcase(self):
		self.help_login()
		self.ghost.click("a[href*='users']", expect_loading=True)
		if 'test_user' in self.ghost.content:
			exit_skipped("test_user already existing")
		self.ghost.click("a#users__action_create")
		self.ghost.wait_for_selector("input[type=submit][value='Create User']") # ajax loading
		tenant_id = re.search(r"\"(\w*)\">openstack<", self.ghost.content, re.M).group(1)
		self.ghost.fill("form#create_user_form", {
			"name": "test_user",
			"email": "tux@suse.de",
			"password": "crowbar1",
			"confirm_password": "crowbar1",
			"tenant_id": tenant_id
		})
		self.ghost.fire_on("form#create_user_form", "submit", expect_loading=True)
		assert '"test_user" was successfully created' in self.ghost.content

if __name__ == '__main__':
	del GhostTestCase
	unittest.main()
