#!/usr/bin/python2

import unittest
import sys, os
sys.path.append(os.path.join(os.path.dirname(sys.argv[0]), '..'))
from base import *

class TestCase(GhostTestCase):
	def do_testcase(self):
		self.help_login()
		self.ghost.click("a[href*='users']", expect_loading=True)
		if not 'test_user' in self.ghost.content:
			exit_skipped("test_user not existing")
		user_id, user_enabled = re.search(r">test_user</td>.*>(\w*)</td>[^>]*>(True|False)<", self.ghost.content, re.M).groups()
		user_enabled = (user_enabled == 'True')
		if not user_enabled:
			exit_skipped("test_user already disabled")
		self.ghost.click("button[value='users__enable__%s']" % user_id, expect_loading=True)
		assert "Disabled User: test_user" in self.ghost.content

if __name__ == '__main__':
	del GhostTestCase
	unittest.main()
