#!/usr/bin/python2

import unittest
import sys, os
sys.path.append(os.path.join(os.path.dirname(sys.argv[0]), '..'))
from base import *

class TestCase(GhostTestCase):
	def do_testcase(self):
		self.assertRaises(AssertionError, self.help_login, username='test_user', password='crowbar1')
		assert "You are not authorized for any available projects" in self.ghost.content

if __name__ == '__main__':
	del GhostTestCase
	unittest.main()
