#!/usr/bin/python2

import unittest
import sys, os
sys.path.append(os.path.join(os.path.dirname(sys.argv[0]), '..'))
from base import *

class TestCase(GhostTestCase):
	def do_testcase(self):
		self.help_login()
		self.ghost.click("a[href*='project/']", expect_loading=True)
		self.help_select_project('openstack')
		self.ghost.click("a[href*='instances']", expect_loading=True)
		if "jeos_00" not in self.ghost.content:
			exit_skipped("jeos_00 not existing")
		instance_id = re.search(r"/([^/]*)/\"[^>]*>jeos_00<", self.ghost.content, re.M).group(1)
		self.ghost.click("button[value='instances__terminate__%s']" % instance_id)
		assert "Confirm Terminate Instance" in self.ghost.content
		self.ghost.click("div.modal-footer a.btn-primary", expect_loading=True)
		assert 'Scheduled termination of Instance: jeos_00' in self.ghost.content

		self.help_wait_instance_gone(instance_id)
		assert not "jeos_00" in self.ghost.content

if __name__ == '__main__':
	del GhostTestCase
	unittest.main()
