#!/usr/bin/python2

import unittest
import sys, os
sys.path.append(os.path.join(os.path.dirname(sys.argv[0]), '..'))
from base import *

class TestCase(GhostTestCase):
	def do_testcase(self):
		self.help_login(username='crowbar')
		assert "<h3>openstack</h3>" in self.ghost.content
		self.ghost.click("a[href*='instances']", expect_loading=True)
		# user can't even see it...
		assert "jeos_03" not in self.ghost.content

if __name__ == '__main__':
	del GhostTestCase
	unittest.main()
