#!/usr/bin/python2

import unittest
import sys, os
sys.path.append(os.path.join(os.path.dirname(sys.argv[0]), '..'))
from base import *

class TestCase(GhostTestCase):
	def do_testcase(self):
		self.help_login(username='crowbar')
		assert "<h3>openstack</h3>" in self.ghost.content
		self.ghost.click("a[href*='instances']", expect_loading=True)
		if "jeos_multiimg" in self.ghost.content:
			exit_skipped("jeos_multiimg already existing")

		image_names = ['jeos1', 'jeos2']

		for image_name in image_names:
			self.ghost.click("a[href*='images']", expect_loading=True)
			image_id = re.search(r"/([^/]*)/\">%s<" % image_name, self.ghost.content, re.M).group(1)
			self.ghost.click("a[href*='%s/launch']" % image_id)
			self.ghost.wait_for_selector("input[type=submit][value='Launch Instance']") # ajax loading
			self.ghost.fill("form#launch_image_form", {
				"name": "jeos_multiimg"
			})
			self.ghost.fire_on("form#launch_image_form", "submit", expect_loading=True)
			assert 'Instance "jeos_multiimg" launched.' in self.ghost.content

		# wait for instances to become active
		instance_ids = re.findall(r"/([^/]*)/detail\">jeos_multiimg<", self.ghost.content, re.M)
		self.assertEqual(len(instance_ids), len(image_names))
		instances_active = {}
		for i in range(0, 30):
			for instance_id in instance_ids:
				if self.ghost.exists("tr#instances__row__%s td.status_up" % instance_id):
					instance_status = self.ghost.evaluate('document.querySelector("tr#instances__row__%s td.status_up").innerHTML;' % instance_id)[0]
				else:
					instance_status = None
				if instance_status == 'Active':
					instances_active[instance_id] = True
			if len(instances_active) == len(image_names):
				break
			sleep(2)
		self.assertEqual(len(instances_active), len(image_names))

		for instance_id in instance_ids:
			self.ghost.click("input[name='object_ids'][value='%s']" % instance_id)
		assert not self.ghost.exists("button#instances__action_terminate.disabled")
		self.ghost.click("button#instances__action_terminate")
		assert "Confirm Terminate Instances" in self.ghost.content
		self.ghost.click("div.modal-footer a.btn-primary", expect_loading=True)
		assert "Terminated Instances: %s" % ', '.join(["jeos_multiimg"] * len(image_names)) in self.ghost.content
		for i in range(0, 30):
			self.ghost.click("a[href*='instances']", expect_loading=True)
			if not "jeos_multiimg" in self.ghost.content:
				break
			sleep(2)
		assert not "jeos_multiimg" in self.ghost.content

if __name__ == '__main__':
	del GhostTestCase
	unittest.main()
